# Generated by Django 2.2.6 on 2019-10-31 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=10, unique=True)),
                ('hiresLifetime', models.PositiveSmallIntegerField(default=0)),
                ('lowresLifetime', models.PositiveSmallIntegerField(default=0)),
                ('logo', models.ImageField(blank=True, upload_to='logo/')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Desabilitado'), (1, 'Habilitado')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.DateTimeField(null=True)),
                ('length', models.PositiveSmallIntegerField(default=0)),
                ('posterURL', models.ImageField(blank=True, upload_to='poster/')),
                ('thumbsURL', models.ImageField(blank=True, upload_to='thumbs/')),
                ('lowresURL', models.URLField(blank=True)),
                ('hiresURL', models.URLField(blank=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Indisponivel'), (1, 'Hires disponivel'), (2, 'Lowres disponivel'), (3, 'Hires e Lowres disponivel')], default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='video.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(max_length=250)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='video.Clip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
